// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cmsg.proto

package com.github.bati;

public final class Cmsg {
  private Cmsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.github.bati.ClientMsgType}
   */
  public enum ClientMsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Unused = 0;</code>
     */
    Unused(0),
    /**
     * <code>Init = 1;</code>
     */
    Init(1),
    /**
     * <code>InitResp = 2;</code>
     */
    InitResp(2),
    /**
     * <code>Biz = 3;</code>
     */
    Biz(3),
    /**
     * <code>Ack = 4;</code>
     */
    Ack(4),
    /**
     * <code>Echo = 100;</code>
     */
    Echo(100),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Unused = 0;</code>
     */
    public static final int Unused_VALUE = 0;
    /**
     * <code>Init = 1;</code>
     */
    public static final int Init_VALUE = 1;
    /**
     * <code>InitResp = 2;</code>
     */
    public static final int InitResp_VALUE = 2;
    /**
     * <code>Biz = 3;</code>
     */
    public static final int Biz_VALUE = 3;
    /**
     * <code>Ack = 4;</code>
     */
    public static final int Ack_VALUE = 4;
    /**
     * <code>Echo = 100;</code>
     */
    public static final int Echo_VALUE = 100;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ClientMsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ClientMsgType forNumber(int value) {
      switch (value) {
        case 0: return Unused;
        case 1: return Init;
        case 2: return InitResp;
        case 3: return Biz;
        case 4: return Ack;
        case 100: return Echo;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ClientMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ClientMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ClientMsgType>() {
            public ClientMsgType findValueByNumber(int number) {
              return ClientMsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Cmsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final ClientMsgType[] VALUES = values();

    public static ClientMsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ClientMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.bati.ClientMsgType)
  }

  /**
   * Protobuf enum {@code com.github.bati.CompressorType}
   */
  public enum CompressorType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Null = 0;</code>
     */
    Null(0),
    /**
     * <code>Deflate = 1;</code>
     */
    Deflate(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Null = 0;</code>
     */
    public static final int Null_VALUE = 0;
    /**
     * <code>Deflate = 1;</code>
     */
    public static final int Deflate_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CompressorType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CompressorType forNumber(int value) {
      switch (value) {
        case 0: return Null;
        case 1: return Deflate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CompressorType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CompressorType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompressorType>() {
            public CompressorType findValueByNumber(int number) {
              return CompressorType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Cmsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final CompressorType[] VALUES = values();

    public static CompressorType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CompressorType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.github.bati.CompressorType)
  }

  public interface ClientMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.bati.ClientMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>.com.github.bati.ClientMsgType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.com.github.bati.ClientMsgType type = 2;</code>
     * @return The type.
     */
    ClientMsgType getType();

    /**
     * <code>int32 ack = 3;</code>
     * @return The ack.
     */
    int getAck();

    /**
     * <code>optional string service_id = 4;</code>
     * @return Whether the serviceId field is set.
     */
    boolean hasServiceId();
    /**
     * <code>optional string service_id = 4;</code>
     * @return The serviceId.
     */
    String getServiceId();
    /**
     * <code>optional string service_id = 4;</code>
     * @return The bytes for serviceId.
     */
    com.google.protobuf.ByteString
        getServiceIdBytes();

    /**
     * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
     * @return Whether the compressor field is set.
     */
    boolean hasCompressor();
    /**
     * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
     * @return The enum numeric value on the wire for compressor.
     */
    int getCompressorValue();
    /**
     * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
     * @return The compressor.
     */
    CompressorType getCompressor();

    /**
     * <code>optional bytes biz_data = 6;</code>
     * @return Whether the bizData field is set.
     */
    boolean hasBizData();
    /**
     * <code>optional bytes biz_data = 6;</code>
     * @return The bizData.
     */
    com.google.protobuf.ByteString getBizData();

    /**
     * <code>optional .com.github.bati.InitData init_data = 7;</code>
     * @return Whether the initData field is set.
     */
    boolean hasInitData();
    /**
     * <code>optional .com.github.bati.InitData init_data = 7;</code>
     * @return The initData.
     */
    InitData getInitData();
    /**
     * <code>optional .com.github.bati.InitData init_data = 7;</code>
     */
    InitDataOrBuilder getInitDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.github.bati.ClientMsg}
   */
  public static final class ClientMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.bati.ClientMsg)
      ClientMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientMsg.newBuilder() to construct.
    private ClientMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientMsg() {
      id_ = "";
      type_ = 0;
      serviceId_ = "";
      compressor_ = 0;
      bizData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {

              ack_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              serviceId_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              bitField0_ |= 0x00000002;
              compressor_ = rawValue;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000004;
              bizData_ = input.readBytes();
              break;
            }
            case 58: {
              InitData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) != 0)) {
                subBuilder = initData_.toBuilder();
              }
              initData_ = input.readMessage(InitData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(initData_);
                initData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmsg.internal_static_com_github_bati_ClientMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmsg.internal_static_com_github_bati_ClientMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientMsg.class, Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.com.github.bati.ClientMsgType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.github.bati.ClientMsgType type = 2;</code>
     * @return The type.
     */
    @Override public ClientMsgType getType() {
      @SuppressWarnings("deprecation")
      ClientMsgType result = ClientMsgType.valueOf(type_);
      return result == null ? ClientMsgType.UNRECOGNIZED : result;
    }

    public static final int ACK_FIELD_NUMBER = 3;
    private int ack_;
    /**
     * <code>int32 ack = 3;</code>
     * @return The ack.
     */
    @Override
    public int getAck() {
      return ack_;
    }

    public static final int SERVICE_ID_FIELD_NUMBER = 4;
    private volatile Object serviceId_;
    /**
     * <code>optional string service_id = 4;</code>
     * @return Whether the serviceId field is set.
     */
    @Override
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string service_id = 4;</code>
     * @return The serviceId.
     */
    @Override
    public String getServiceId() {
      Object ref = serviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string service_id = 4;</code>
     * @return The bytes for serviceId.
     */
    @Override
    public com.google.protobuf.ByteString
        getServiceIdBytes() {
      Object ref = serviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPRESSOR_FIELD_NUMBER = 5;
    private int compressor_;
    /**
     * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
     * @return Whether the compressor field is set.
     */
    @Override public boolean hasCompressor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
     * @return The enum numeric value on the wire for compressor.
     */
    @Override public int getCompressorValue() {
      return compressor_;
    }
    /**
     * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
     * @return The compressor.
     */
    @Override public CompressorType getCompressor() {
      @SuppressWarnings("deprecation")
      CompressorType result = CompressorType.valueOf(compressor_);
      return result == null ? CompressorType.UNRECOGNIZED : result;
    }

    public static final int BIZ_DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString bizData_;
    /**
     * <code>optional bytes biz_data = 6;</code>
     * @return Whether the bizData field is set.
     */
    @Override
    public boolean hasBizData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes biz_data = 6;</code>
     * @return The bizData.
     */
    @Override
    public com.google.protobuf.ByteString getBizData() {
      return bizData_;
    }

    public static final int INIT_DATA_FIELD_NUMBER = 7;
    private InitData initData_;
    /**
     * <code>optional .com.github.bati.InitData init_data = 7;</code>
     * @return Whether the initData field is set.
     */
    @Override
    public boolean hasInitData() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .com.github.bati.InitData init_data = 7;</code>
     * @return The initData.
     */
    @Override
    public InitData getInitData() {
      return initData_ == null ? InitData.getDefaultInstance() : initData_;
    }
    /**
     * <code>optional .com.github.bati.InitData init_data = 7;</code>
     */
    @Override
    public InitDataOrBuilder getInitDataOrBuilder() {
      return initData_ == null ? InitData.getDefaultInstance() : initData_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (type_ != ClientMsgType.Unused.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (ack_ != 0) {
        output.writeInt32(3, ack_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serviceId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(5, compressor_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(6, bizData_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(7, getInitData());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (type_ != ClientMsgType.Unused.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (ack_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ack_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serviceId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, compressor_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, bizData_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getInitData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientMsg)) {
        return super.equals(obj);
      }
      ClientMsg other = (ClientMsg) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (type_ != other.type_) return false;
      if (getAck()
          != other.getAck()) return false;
      if (hasServiceId() != other.hasServiceId()) return false;
      if (hasServiceId()) {
        if (!getServiceId()
            .equals(other.getServiceId())) return false;
      }
      if (hasCompressor() != other.hasCompressor()) return false;
      if (hasCompressor()) {
        if (compressor_ != other.compressor_) return false;
      }
      if (hasBizData() != other.hasBizData()) return false;
      if (hasBizData()) {
        if (!getBizData()
            .equals(other.getBizData())) return false;
      }
      if (hasInitData() != other.hasInitData()) return false;
      if (hasInitData()) {
        if (!getInitData()
            .equals(other.getInitData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ACK_FIELD_NUMBER;
      hash = (53 * hash) + getAck();
      if (hasServiceId()) {
        hash = (37 * hash) + SERVICE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getServiceId().hashCode();
      }
      if (hasCompressor()) {
        hash = (37 * hash) + COMPRESSOR_FIELD_NUMBER;
        hash = (53 * hash) + compressor_;
      }
      if (hasBizData()) {
        hash = (37 * hash) + BIZ_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getBizData().hashCode();
      }
      if (hasInitData()) {
        hash = (37 * hash) + INIT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getInitData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ClientMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.bati.ClientMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.bati.ClientMsg)
        ClientMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmsg.internal_static_com_github_bati_ClientMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmsg.internal_static_com_github_bati_ClientMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientMsg.class, Builder.class);
      }

      // Construct using com.github.bati.Cmsg.ClientMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInitDataFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        type_ = 0;

        ack_ = 0;

        serviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        compressor_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bizData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (initDataBuilder_ == null) {
          initData_ = null;
        } else {
          initDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmsg.internal_static_com_github_bati_ClientMsg_descriptor;
      }

      @Override
      public ClientMsg getDefaultInstanceForType() {
        return ClientMsg.getDefaultInstance();
      }

      @Override
      public ClientMsg build() {
        ClientMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ClientMsg buildPartial() {
        ClientMsg result = new ClientMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.type_ = type_;
        result.ack_ = ack_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serviceId_ = serviceId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.compressor_ = compressor_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bizData_ = bizData_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          if (initDataBuilder_ == null) {
            result.initData_ = initData_;
          } else {
            result.initData_ = initDataBuilder_.build();
          }
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientMsg) {
          return mergeFrom((ClientMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientMsg other) {
        if (other == ClientMsg.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getAck() != 0) {
          setAck(other.getAck());
        }
        if (other.hasServiceId()) {
          bitField0_ |= 0x00000001;
          serviceId_ = other.serviceId_;
          onChanged();
        }
        if (other.hasCompressor()) {
          setCompressor(other.getCompressor());
        }
        if (other.hasBizData()) {
          setBizData(other.getBizData());
        }
        if (other.hasInitData()) {
          mergeInitData(other.getInitData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ClientMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ClientMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.com.github.bati.ClientMsgType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.github.bati.ClientMsgType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.bati.ClientMsgType type = 2;</code>
       * @return The type.
       */
      @Override
      public ClientMsgType getType() {
        @SuppressWarnings("deprecation")
        ClientMsgType result = ClientMsgType.valueOf(type_);
        return result == null ? ClientMsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.github.bati.ClientMsgType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(ClientMsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.bati.ClientMsgType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int ack_ ;
      /**
       * <code>int32 ack = 3;</code>
       * @return The ack.
       */
      @Override
      public int getAck() {
        return ack_;
      }
      /**
       * <code>int32 ack = 3;</code>
       * @param value The ack to set.
       * @return This builder for chaining.
       */
      public Builder setAck(int value) {
        
        ack_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ack = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAck() {
        
        ack_ = 0;
        onChanged();
        return this;
      }

      private Object serviceId_ = "";
      /**
       * <code>optional string service_id = 4;</code>
       * @return Whether the serviceId field is set.
       */
      public boolean hasServiceId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string service_id = 4;</code>
       * @return The serviceId.
       */
      public String getServiceId() {
        Object ref = serviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string service_id = 4;</code>
       * @return The bytes for serviceId.
       */
      public com.google.protobuf.ByteString
          getServiceIdBytes() {
        Object ref = serviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_id = 4;</code>
       * @param value The serviceId to set.
       * @return This builder for chaining.
       */
      public Builder setServiceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearServiceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serviceId_ = getDefaultInstance().getServiceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_id = 4;</code>
       * @param value The bytes for serviceId to set.
       * @return This builder for chaining.
       */
      public Builder setServiceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        serviceId_ = value;
        onChanged();
        return this;
      }

      private int compressor_ = 0;
      /**
       * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
       * @return Whether the compressor field is set.
       */
      @Override public boolean hasCompressor() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
       * @return The enum numeric value on the wire for compressor.
       */
      @Override public int getCompressorValue() {
        return compressor_;
      }
      /**
       * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
       * @param value The enum numeric value on the wire for compressor to set.
       * @return This builder for chaining.
       */
      public Builder setCompressorValue(int value) {
        bitField0_ |= 0x00000002;
        compressor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
       * @return The compressor.
       */
      @Override
      public CompressorType getCompressor() {
        @SuppressWarnings("deprecation")
        CompressorType result = CompressorType.valueOf(compressor_);
        return result == null ? CompressorType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
       * @param value The compressor to set.
       * @return This builder for chaining.
       */
      public Builder setCompressor(CompressorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        compressor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.github.bati.CompressorType compressor = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompressor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        compressor_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bizData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes biz_data = 6;</code>
       * @return Whether the bizData field is set.
       */
      @Override
      public boolean hasBizData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes biz_data = 6;</code>
       * @return The bizData.
       */
      @Override
      public com.google.protobuf.ByteString getBizData() {
        return bizData_;
      }
      /**
       * <code>optional bytes biz_data = 6;</code>
       * @param value The bizData to set.
       * @return This builder for chaining.
       */
      public Builder setBizData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        bizData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes biz_data = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBizData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bizData_ = getDefaultInstance().getBizData();
        onChanged();
        return this;
      }

      private InitData initData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          InitData, InitData.Builder, InitDataOrBuilder> initDataBuilder_;
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       * @return Whether the initData field is set.
       */
      public boolean hasInitData() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       * @return The initData.
       */
      public InitData getInitData() {
        if (initDataBuilder_ == null) {
          return initData_ == null ? InitData.getDefaultInstance() : initData_;
        } else {
          return initDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      public Builder setInitData(InitData value) {
        if (initDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          initData_ = value;
          onChanged();
        } else {
          initDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      public Builder setInitData(
          InitData.Builder builderForValue) {
        if (initDataBuilder_ == null) {
          initData_ = builderForValue.build();
          onChanged();
        } else {
          initDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      public Builder mergeInitData(InitData value) {
        if (initDataBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
              initData_ != null &&
              initData_ != InitData.getDefaultInstance()) {
            initData_ =
              InitData.newBuilder(initData_).mergeFrom(value).buildPartial();
          } else {
            initData_ = value;
          }
          onChanged();
        } else {
          initDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      public Builder clearInitData() {
        if (initDataBuilder_ == null) {
          initData_ = null;
          onChanged();
        } else {
          initDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      public InitData.Builder getInitDataBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getInitDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      public InitDataOrBuilder getInitDataOrBuilder() {
        if (initDataBuilder_ != null) {
          return initDataBuilder_.getMessageOrBuilder();
        } else {
          return initData_ == null ?
              InitData.getDefaultInstance() : initData_;
        }
      }
      /**
       * <code>optional .com.github.bati.InitData init_data = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          InitData, InitData.Builder, InitDataOrBuilder>
          getInitDataFieldBuilder() {
        if (initDataBuilder_ == null) {
          initDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              InitData, InitData.Builder, InitDataOrBuilder>(
                  getInitData(),
                  getParentForChildren(),
                  isClean());
          initData_ = null;
        }
        return initDataBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.bati.ClientMsg)
    }

    // @@protoc_insertion_point(class_scope:com.github.bati.ClientMsg)
    private static final ClientMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientMsg();
    }

    public static ClientMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientMsg>
        PARSER = new com.google.protobuf.AbstractParser<ClientMsg>() {
      @Override
      public ClientMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ClientMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public ClientMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InitDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.bati.InitData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
     * @return The enum numeric value on the wire for acceptCompressor.
     */
    int getAcceptCompressorValue();
    /**
     * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
     * @return The acceptCompressor.
     */
    CompressorType getAcceptCompressor();

    /**
     * <code>uint32 ping_interval = 2;</code>
     * @return The pingInterval.
     */
    int getPingInterval();
  }
  /**
   * Protobuf type {@code com.github.bati.InitData}
   */
  public static final class InitData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.bati.InitData)
      InitDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InitData.newBuilder() to construct.
    private InitData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InitData() {
      acceptCompressor_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InitData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InitData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              acceptCompressor_ = rawValue;
              break;
            }
            case 16: {

              pingInterval_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Cmsg.internal_static_com_github_bati_InitData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Cmsg.internal_static_com_github_bati_InitData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InitData.class, Builder.class);
    }

    public static final int ACCEPT_COMPRESSOR_FIELD_NUMBER = 1;
    private int acceptCompressor_;
    /**
     * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
     * @return The enum numeric value on the wire for acceptCompressor.
     */
    @Override public int getAcceptCompressorValue() {
      return acceptCompressor_;
    }
    /**
     * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
     * @return The acceptCompressor.
     */
    @Override public CompressorType getAcceptCompressor() {
      @SuppressWarnings("deprecation")
      CompressorType result = CompressorType.valueOf(acceptCompressor_);
      return result == null ? CompressorType.UNRECOGNIZED : result;
    }

    public static final int PING_INTERVAL_FIELD_NUMBER = 2;
    private int pingInterval_;
    /**
     * <code>uint32 ping_interval = 2;</code>
     * @return The pingInterval.
     */
    @Override
    public int getPingInterval() {
      return pingInterval_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (acceptCompressor_ != CompressorType.Null.getNumber()) {
        output.writeEnum(1, acceptCompressor_);
      }
      if (pingInterval_ != 0) {
        output.writeUInt32(2, pingInterval_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (acceptCompressor_ != CompressorType.Null.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, acceptCompressor_);
      }
      if (pingInterval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, pingInterval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InitData)) {
        return super.equals(obj);
      }
      InitData other = (InitData) obj;

      if (acceptCompressor_ != other.acceptCompressor_) return false;
      if (getPingInterval()
          != other.getPingInterval()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCEPT_COMPRESSOR_FIELD_NUMBER;
      hash = (53 * hash) + acceptCompressor_;
      hash = (37 * hash) + PING_INTERVAL_FIELD_NUMBER;
      hash = (53 * hash) + getPingInterval();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InitData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InitData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InitData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InitData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InitData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InitData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InitData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InitData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InitData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.bati.InitData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.bati.InitData)
        InitDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Cmsg.internal_static_com_github_bati_InitData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Cmsg.internal_static_com_github_bati_InitData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InitData.class, Builder.class);
      }

      // Construct using com.github.bati.Cmsg.InitData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        acceptCompressor_ = 0;

        pingInterval_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Cmsg.internal_static_com_github_bati_InitData_descriptor;
      }

      @Override
      public InitData getDefaultInstanceForType() {
        return InitData.getDefaultInstance();
      }

      @Override
      public InitData build() {
        InitData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public InitData buildPartial() {
        InitData result = new InitData(this);
        result.acceptCompressor_ = acceptCompressor_;
        result.pingInterval_ = pingInterval_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InitData) {
          return mergeFrom((InitData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InitData other) {
        if (other == InitData.getDefaultInstance()) return this;
        if (other.acceptCompressor_ != 0) {
          setAcceptCompressorValue(other.getAcceptCompressorValue());
        }
        if (other.getPingInterval() != 0) {
          setPingInterval(other.getPingInterval());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InitData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InitData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int acceptCompressor_ = 0;
      /**
       * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
       * @return The enum numeric value on the wire for acceptCompressor.
       */
      @Override public int getAcceptCompressorValue() {
        return acceptCompressor_;
      }
      /**
       * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
       * @param value The enum numeric value on the wire for acceptCompressor to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptCompressorValue(int value) {
        
        acceptCompressor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
       * @return The acceptCompressor.
       */
      @Override
      public CompressorType getAcceptCompressor() {
        @SuppressWarnings("deprecation")
        CompressorType result = CompressorType.valueOf(acceptCompressor_);
        return result == null ? CompressorType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
       * @param value The acceptCompressor to set.
       * @return This builder for chaining.
       */
      public Builder setAcceptCompressor(CompressorType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        acceptCompressor_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.github.bati.CompressorType accept_compressor = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAcceptCompressor() {
        
        acceptCompressor_ = 0;
        onChanged();
        return this;
      }

      private int pingInterval_ ;
      /**
       * <code>uint32 ping_interval = 2;</code>
       * @return The pingInterval.
       */
      @Override
      public int getPingInterval() {
        return pingInterval_;
      }
      /**
       * <code>uint32 ping_interval = 2;</code>
       * @param value The pingInterval to set.
       * @return This builder for chaining.
       */
      public Builder setPingInterval(int value) {
        
        pingInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ping_interval = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPingInterval() {
        
        pingInterval_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.bati.InitData)
    }

    // @@protoc_insertion_point(class_scope:com.github.bati.InitData)
    private static final InitData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InitData();
    }

    public static InitData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InitData>
        PARSER = new com.google.protobuf.AbstractParser<InitData>() {
      @Override
      public InitData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InitData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InitData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InitData> getParserForType() {
      return PARSER;
    }

    @Override
    public InitData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_bati_ClientMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_bati_ClientMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_bati_InitData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_bati_InitData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ncmsg.proto\022\017com.github.bati\"\250\002\n\tClient" +
      "Msg\022\n\n\002id\030\001 \001(\t\022,\n\004type\030\002 \001(\0162\036.com.gith" +
      "ub.bati.ClientMsgType\022\013\n\003ack\030\003 \001(\005\022\027\n\nse" +
      "rvice_id\030\004 \001(\tH\000\210\001\001\0228\n\ncompressor\030\005 \001(\0162" +
      "\037.com.github.bati.CompressorTypeH\001\210\001\001\022\025\n" +
      "\010biz_data\030\006 \001(\014H\002\210\001\001\0221\n\tinit_data\030\007 \001(\0132" +
      "\031.com.github.bati.InitDataH\003\210\001\001B\r\n\013_serv" +
      "ice_idB\r\n\013_compressorB\013\n\t_biz_dataB\014\n\n_i" +
      "nit_data\"]\n\010InitData\022:\n\021accept_compresso" +
      "r\030\001 \001(\0162\037.com.github.bati.CompressorType" +
      "\022\025\n\rping_interval\030\002 \001(\r*O\n\rClientMsgType" +
      "\022\n\n\006Unused\020\000\022\010\n\004Init\020\001\022\014\n\010InitResp\020\002\022\007\n\003" +
      "Biz\020\003\022\007\n\003Ack\020\004\022\010\n\004Echo\020d*\'\n\016CompressorTy" +
      "pe\022\010\n\004Null\020\000\022\013\n\007Deflate\020\001B\030Z\026github.com/" +
      "batigo/cmsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_bati_ClientMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_bati_ClientMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_bati_ClientMsg_descriptor,
        new String[] { "Id", "Type", "Ack", "ServiceId", "Compressor", "BizData", "InitData", "ServiceId", "Compressor", "BizData", "InitData", });
    internal_static_com_github_bati_InitData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_github_bati_InitData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_bati_InitData_descriptor,
        new String[] { "AcceptCompressor", "PingInterval", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
